default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: kingno3l
  host: localhost
  pool: 5

development:
  <<: *default
  database: hello_rails_react_development

test:
  <<: *default
  database: hello_rails_react_test

production:
  <<: *default
  database: hello_rails_react_production
  username: hello_rails_react
  password: kingno3l
